### ISSUE TITLE
MQTT Not Discovery

### ISSUE THREAD

**Issue by hostdown** [debsahu/PCF8574_8Relay#5]
Hi, i compile the code, and all OK, but on my homeassistant installation not appear the device automatically, i have configure correctly MQTT Broker, and i have installed too zigbee2mqtt.

Im using the software MQTT Explorer and i see perfectly, and i can access to website to switch ON/OFF, i search a lot and i dont know what more can i do.
Dont receive any error, only dont discovery.

I try disable zigbee2mqtt, force discovery on configuration.yaml, and nothing appear... i dont know what more can i do.

My homeassistant version is 0.108.6 on Linux Ubuntu 18.08 Server, MQTT Broker 5.1 and zigbee2mqtt 1.12.2.

Please, help!! Thank u.

**Comment by debsahu** [comment]
Did you turn on MQTT discovery on home assistant? https://www.home-assistant.io/docs/mqtt/discovery/

**Comment by hostdown** [comment]
Yes i have, this lines on the configuration.yaml 

discovery:
  ignore:
    - sonos
    - samsung_printer
  enable:
    - homekit

mqtt:
  broker: localhost
  discovery: true
  discovery_prefix: homeassistant

im trying all the time, making changes and nothing...
the mqtt explorer work fine, and see them

* and the mqtt broker tell me that a client connect, so....

**Comment by debsahu** [comment]
Check if it shows up in Configuration > Integrations > MQTT

**Comment by hostdown** [comment]
Okk!! Noww!!
I dont know why, but discovery not work correctly.

I see the switches on Configuration > Entity
So... i create a new UI tab, and add a Entity Card, i select all, and thats all Ok.

Thank u for all ur help!! Thank u!!!
